version: "2"

services:
  web:
    image: gitea/gitea:1.12.4
    container_name:
      docker_gitea_1
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=123456
    volumes:
      - $PATH_WWW_DATA/gitea:/data
    ports:
      - "3000:3000"
      - "22:22"
    depends_on:
      - db
    links:
      - db
    restart: always
  db:
    image: mysql:5.6
    container_name:
      docker_mysql_1
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=123456
    volumes:
      - $PATH_WWW_DATA/mysql:/var/lib/mysql
      - $PATH_WWW_LOG/mysql:/var/log/mysql
    restart: always
