version: "2"

services:
  web:
    image: gitea/gitea:1.12.4
    container_name:
      docker_gitea_1
    volumes:
      - $PATH_WWW_DATA/gitea:/data
    ports:
      - "3000:3000"
      - "22:22"
    depends_on:
      - db
    restart: always
  db:
    image: mariadb:10
    container_name:
      docker_mariadb_1
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=123456
    volumes:
      - $PATH_WWW_DATA/mariadb:/var/lib/mysql
